### ISSUE TITLE
Formspree form

### ISSUE THREAD

**Issue by aammd** [bios2/bios2-website#3]
I've configured it (i think!?) but nothing appears to be happening. When i fill in the form on the Contact page and click submit, nothing at all appears to be happening. Check the instructions again and go over it.

**Comment by aammd** [comment]
Could this be part of the solution? https://github.com/devcows/hugo-universal-theme/pull/152/files  

There are only two changes to make here. i thought i could use git to bring these changes together with the current directory. However, that's not possible because blogdown doesn't clone a theme's git repository

I suppose i could either manually make those changes, or download and replace the theme directory

**Comment by tpoisot** [comment]
Can't you specify the branch / SHA of the theme instead of the repo?

**Comment by aammd** [comment]
this now works! Not sure if caused by my experimentations or luck or time. closing
